server: 
  port: 8080
mysql:
  host: localhost
  port: 3306
  username: root
  password: root1234
  dbname: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
log:
  log_level: debug
  file_log_name: "./storages/logs/dev.001.log"
  max_size:    500
  max_backups: 3
  max_age:     28
  compress:   true
redis:
  host: localhost
  port: 6379
  password: ""
  database: 0
